### ISSUE TITLE
Remove generated files from GIT

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/jpl.imce.oml.specification.parent#7]
Currently, most generated files are in GIT.
However, this causes some problems:

- Eclipse `.classpath` 

  These have host-specific paths. In principle, Gradle can generate them. This needs to be tested.

- EMF metamodels & generated API/implementation

  The Eclipse Xcore tooling generates both API & implementation in Java as well as
  an EMF ecore metamodel. Unfortunately, the XMI-based serialization of that metamodel
  varies. Since the meta model is generated anyway, it should be OK to remove it and the
  generated API/implementation from GIT. 

- Xtend generated code

  There is some variation in the generated Java code.
  The`@Override` annotation is not always in the generated code.
  Sometimes, names of function arguments change from some generic name (e.g. `arg1`) 
  to a name from the Xtend source & vice-versa.

Removing generated files needs to be explained properly
because the project will need to be built before it is imported in an IDE (Eclipse, IntelliJ, ...)

**Comment by sjiherzig** [comment]
The discrepancy of `@Override` usage could be due to different Java SDK versions being used to build the project. As far as I remember, some don't like `@Override`.

Removing the generated code from git is preferred.

@NicolasRouquette : why does the project need to be built before it is imported into Eclipse? This is a pattern I've only seen with IntelliJ+SBT thus far.

**Comment by NicolasRouquette** [comment]
Removing generated files would include both generated code and project metadata (e.g. `.classpath`), without which Eclipse will be utterly confused.

Typically, I see variation when Eclipse' project builder kicks in.
It's configured to use Java 1.8 AFAIK.
It's bizarre that there would be qualitatively significant variation from one "build" to another when nothing in the environment/setting has changed.
